language: java

addons:
  sonarcloud:
    organization: "fredboat"

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"
    - secure: "Cgx8CCMr7EeIAqpSgXQr+M3aAXXbv4O6xgFtMw758G/1C5bFYanu1bVXM9BzIENpjBD2fImZbztDNvrPh+sGzE1PCEYNxeH+vIHAUaSBM2p+dC6IEeT2mcJWhn36IFmPWerWI9uUBg4/e9jbFhxHSUqJcs7D0w0cnSQlcw2qIQxf7P+TFe0q23usdAoB6mkBohIPHMKiQ5TNFzMUAMcRt1sSyA6qriaozsMNhKUTLeoFFysrmXygcr5GsCVMJI/3narWKKS4Rd3yfKdpSfV1zVL7L1UOjULhl8gdOsR4YmqlsA4Jbk8yDSGyaYDtOomy7dcdjCMkMqc61jLd/4cn+4ZQEWuO8f9Oe/nFqwXeTryfBviBHijFaP91K31W81lsH0a1NH56me9fxZTeTKvhuzmQs+l9GNka+ANI38GMVzW1fXS++JwbtCva184pgi3hxLpEvZuoc0XANvVOXf9pnmD7JxEiFWLHX+Gj1tymyj9idMbBnP31xB4TKWhbvRa1tqCWLnARQ19dyytapc7ddWdxWF/H9Qx/ErwK5jMgScAyPas+4dAGip618BSjPhToECeKmF0ABqubRqbNY3EoPjUsRyICdsNdEW+iU5nt1USw6FKu3VdYdAu4lRP/hB/afLON/jkM2dS5LKGveFXzCHWys5snj1kMn3saFa8dk84="

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - ".gradle/wrapper"
    - ".gradle/caches"
    - "$HOME/.sonar/cache"

stages:
  - sonar

jobs:
  fast_finish: true
  include:
    - stage: sonar
      jdk: openjdk16
      if: env(TRAVIS_SECURE_ENV_VARS) = true
      before_script:
        #for full sonar cloud blame information
        - "git fetch --depth=10000"
      script:
        - "./gradlew sonarqube"
